#!/usr/bin/env python3
"""
ERR0RS ULTIMATE - Auto Tool Generator
Automatically generates tool integrations for EVERY security tool!

This is REVOLUTIONARY - we can integrate 150+ tools in SECONDS!
"""

import asyncio
import os
from pathlib import Path
from typing import List
from .universal_adapter import UniversalToolAdapter, DiscoveredTool


class AutoToolGenerator:
    """
    AUTO TOOL GENERATOR
    
    Automatically creates Python wrappers for ALL discovered tools!
    150+ tools integrated in seconds instead of weeks!
    """
    
    def __init__(self, output_dir: str = "src/tools/auto_generated"):
        self.output_dir = Path(output_dir)
        self.adapter = UniversalToolAdapter()
        self.generated_count = 0
        
    async def generate_all_integrations(self):
        """
        GENERATE ALL TOOL INTEGRATIONS AUTOMATICALLY!
        
        This is the game-changer!
        """
        
        print("\n" + "="*70)
        print("🚀 AUTO TOOL GENERATOR - STARTING")
        print("="*70)
        print("\nThis will automatically integrate EVERY security tool on your system!")
        print("No manual coding needed - AI does it all!\n")
        
        # Step 1: Discover all tools
        print("📡 Step 1: Discovering tools...")
        tools = await self.adapter.discover_all_tools()
        
        # Step 2: Create output directories
        print("\n📁 Step 2: Creating directory structure...")
        self._create_directories(tools)
        
        # Step 3: Generate wrappers
        print("\n🔧 Step 3: Generating tool wrappers...")
        await self._generate_all_wrappers(tools)
        
        # Step 4: Generate category indexes
        print("\n📝 Step 4: Creating category indexes...")
        self._generate_category_indexes(tools)
        
        # Step 5: Generate master registry
        print("\n📋 Step 5: Building master tool registry...")
        self._generate_master_registry(tools)
        
        print("\n" + "="*70)
        print(f"✅ AUTO GENERATION COMPLETE!")
        print("="*70)
        print(f"\n🎉 Successfully generated {self.generated_count} tool integrations!")
        print(f"📂 Location: {self.output_dir}")
        print(f"\nYou can now use ANY of these tools through ERR0RS ULTIMATE!\n")
        
        return tools
    
    def _create_directories(self, tools: List[DiscoveredTool]):
        """Create directory structure by category"""
        
        # Get unique categories
        categories = set(tool.category for tool in tools)
        
        # Create main directory
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Create category directories
        for category in categories:
            category_dir = self.output_dir / category
            category_dir.mkdir(exist_ok=True)
            
            # Create __init__.py
            init_file = category_dir / "__init__.py"
            init_file.write_text(f'"""Auto-generated {category} tools"""\n')
        
        print(f"   Created {len(categories)} category directories")
    
    async def _generate_all_wrappers(self, tools: List[DiscoveredTool]):
        """Generate wrapper for each tool"""
        
        for i, tool in enumerate(tools, 1):
            print(f"   [{i}/{len(tools)}] Generating {tool.name}...", end="")
            
            # Generate wrapper code
            wrapper_code = self.adapter.generate_tool_wrapper(tool.name)
            
            # Write to file
            category_dir = self.output_dir / tool.category
            tool_file = category_dir / f"{tool.name.replace('-', '_')}.py"
            
            tool_file.write_text(wrapper_code)
            
            self.generated_count += 1
            print(" ✅")
            
            # Small delay to avoid overwhelming
            await asyncio.sleep(0.01)
    
    def _generate_category_indexes(self, tools: List[DiscoveredTool]):
        """Generate __init__.py for each category"""
        
        # Group tools by category
        by_category = {}
        for tool in tools:
            if tool.category not in by_category:
                by_category[tool.category] = []
            by_category[tool.category].append(tool)
        
        # Generate index for each category
        for category, category_tools in by_category.items():
            category_dir = self.output_dir / category
            init_file = category_dir / "__init__.py"
            
            # Generate imports
            imports = []
            exports = []
            
            for tool in category_tools:
                class_name = f"{tool.name.title().replace('-', '')}Tool"
                module_name = tool.name.replace('-', '_')
                imports.append(f"from .{module_name} import {class_name}")
                exports.append(f"'{class_name}'")
            
            # Write file
            content = f'''"""
Auto-generated {category} tools
Generated by ERR0RS ULTIMATE Auto Tool Generator
Total tools: {len(category_tools)}
"""

{chr(10).join(imports)}

__all__ = [
    {', '.join(exports)}
]
'''
            
            init_file.write_text(content)
        
        print(f"   Generated {len(by_category)} category indexes")
    
    def _generate_master_registry(self, tools: List[DiscoveredTool]):
        """Generate master tool registry"""
        
        registry_file = self.output_dir / "tool_registry.py"
        
        # Generate imports by category
        imports = []
        registry_entries = []
        
        by_category = {}
        for tool in tools:
            if tool.category not in by_category:
                by_category[tool.category] = []
            by_category[tool.category].append(tool)
        
        for category, category_tools in by_category.items():
            for tool in category_tools:
                class_name = f"{tool.name.title().replace('-', '')}Tool"
                imports.append(f"from .{category}.{tool.name.replace('-', '_')} import {class_name}")
                registry_entries.append(f'    "{tool.name}": {class_name},')
        
        content = f'''#!/usr/bin/env python3
"""
ERR0RS ULTIMATE - Master Tool Registry
Auto-generated registry of ALL integrated tools

Total tools: {len(tools)}
Generated: {__import__('datetime').datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

This file was AUTO-GENERATED by the ERR0RS ULTIMATE Auto Tool Generator!
"""

{chr(10).join(imports)}


# Master tool registry - ALL tools available!
TOOL_REGISTRY = {{
{chr(10).join(registry_entries)}
}}


# Quick access functions
def get_tool(name: str):
    """Get tool instance by name"""
    tool_class = TOOL_REGISTRY.get(name.lower())
    if not tool_class:
        raise ValueError(f"Tool '{{name}}' not found in registry")
    return tool_class()


def list_tools() -> list:
    """List all available tools"""
    return sorted(TOOL_REGISTRY.keys())


def list_by_category() -> dict:
    """List tools grouped by category"""
    by_category = {{}}
    for name, tool_class in TOOL_REGISTRY.items():
        tool = tool_class()
        category = tool.category.value
        if category not in by_category:
            by_category[category] = []
        by_category[category].append(name)
    return by_category


def get_tool_count() -> int:
    """Get total number of integrated tools"""
    return len(TOOL_REGISTRY)


# Statistics
TOTAL_TOOLS = {len(tools)}
CATEGORIES = {len(by_category)}
AUTO_GENERATED = True

print(f"📊 ERR0RS ULTIMATE Tool Registry Loaded!")
print(f"   Total tools: {{TOTAL_TOOLS}}")
print(f"   Categories: {{CATEGORIES}}")
print(f"   Status: Ready for autonomous operation!")
'''
        
        registry_file.write_text(content)
        print(f"   Master registry created with {len(tools)} tools")
    
    async def generate_documentation(self, tools: List[DiscoveredTool]):
        """Generate comprehensive tool documentation"""
        
        doc_file = self.output_dir / "TOOLS_DOCUMENTATION.md"
        
        # Group by category
        by_category = {}
        for tool in tools:
            if tool.category not in by_category:
                by_category[tool.category] = []
            by_category[tool.category].append(tool)
        
        # Generate markdown
        content = f"""# 🔧 ERR0RS ULTIMATE - Complete Tool Documentation

**Auto-Generated Tool Integration Documentation**

Total Integrated Tools: **{len(tools)}**
Categories: **{len(by_category)}**
Generation Date: {__import__('datetime').datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## 📊 Tools by Category

"""
        
        for category in sorted(by_category.keys()):
            category_tools = by_category[category]
            content += f"\n### {category.upper()} ({len(category_tools)} tools)\n\n"
            
            for tool in sorted(category_tools, key=lambda t: t.name):
                content += f"#### {tool.name}\n"
                content += f"- **Version:** {tool.version}\n"
                content += f"- **Description:** {tool.description}\n"
                content += f"- **Path:** `{tool.binary_path}`\n"
                
                if tool.syntax_patterns:
                    content += f"- **Usage:** `{tool.syntax_patterns[0]}`\n"
                
                content += "\n"
        
        content += """
---

## 🚀 Usage Examples

### Get a tool instance:
```python
from src.tools.auto_generated.tool_registry import get_tool

# Get nmap
nmap = get_tool("nmap")

# Execute
result = await nmap.execute(target="example.com")
```

### List all tools:
```python
from src.tools.auto_generated.tool_registry import list_tools, list_by_category

# All tools
all_tools = list_tools()
print(f"Available tools: {len(all_tools)}")

# By category
by_cat = list_by_category()
for category, tools in by_cat.items():
    print(f"{category}: {len(tools)} tools")
```

### Use with Natural Language:
```bash
errorz "use nmap to scan example.com"
errorz "run sqlmap on http://target.com"
errorz "crack hash with hashcat"
```

---

*Auto-generated by ERR0RS ULTIMATE*
*Making every security tool accessible through AI!*
"""
        
        doc_file.write_text(content)
        print(f"   Documentation generated: {doc_file}")


# Main execution
if __name__ == "__main__":
    async def main():
        generator = AutoToolGenerator()
        
        print("\n🎯 ERR0RS ULTIMATE - AUTO TOOL GENERATOR")
        print("   Preparing to integrate EVERY security tool automatically...\n")
        
        input("Press ENTER to start auto-generation...")
        
        # Generate everything
        tools = await generator.generate_all_integrations()
        
        # Generate documentation
        await generator.generate_documentation(tools)
        
        print("\n" + "="*70)
        print("🎉 SUCCESS!")
        print("="*70)
        print(f"""
All tools are now integrated and ready to use!

Quick start:
1. Import the registry: from src.tools.auto_generated import tool_registry
2. Get any tool: tool = tool_registry.get_tool("nmap")
3. Use it: result = await tool.execute(target="example.com")

Or just use natural language:
   errorz "scan example.com with nmap"

Every security tool on your system is now AI-powered!
""")
    
    asyncio.run(main())
