"""
ERR0RS Report Generator
═══════════════════════
Turns the OperatorState (history + findings) into a professional
HTML pentest report. Pure Python, no external deps.
"""
import html, time, json, os
from pathlib import Path


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<title>ERR0RS Pentest Report — {target}</title>
<style>
  :root {{
    --bg:#0a0015; --panel:#130128; --purple:#7b2fbe; --purple-hi:#c084fc;
    --cyan:#00d7ff; --green:#00ff88; --amber:#ffaa00; --red:#ff3355;
    --text:#e0d5f0; --dim:#8876a8;
  }}
  * {{ box-sizing:border-box; margin:0; padding:0; }}
  body {{
    background:var(--bg); color:var(--text); font-family:-apple-system,
    'Segoe UI',system-ui,sans-serif; padding:2rem; line-height:1.6;
  }}
  h1,h2,h3 {{ font-family:'Orbitron',monospace; letter-spacing:.05em; }}
  h1 {{ color:var(--cyan); border-bottom:2px solid var(--purple); padding-bottom:.5rem; }}
  h2 {{ color:var(--purple-hi); margin:2rem 0 1rem; }}
  h3 {{ color:var(--cyan); margin:1.5rem 0 .5rem; }}
  .banner {{
    background:linear-gradient(135deg,rgba(123,47,190,.2),rgba(0,215,255,.1));
    border:1px solid var(--purple); padding:1.5rem; border-radius:8px;
    margin-bottom:2rem;
  }}
  .meta {{ display:grid; grid-template-columns:repeat(4,1fr); gap:1rem; margin-top:1rem; }}
  .meta div {{ background:var(--panel); padding:.8rem; border-radius:4px;
              border-left:3px solid var(--cyan); }}
  .meta .k {{ color:var(--dim); font-size:.75rem; text-transform:uppercase;
              letter-spacing:.1em; }}
  .meta .v {{ color:var(--cyan); font-size:1.3rem; font-weight:700;
              font-family:'Orbitron',monospace; }}
  .finding {{
    background:var(--panel); padding:1rem; margin:.6rem 0; border-radius:4px;
    border-left:4px solid var(--dim);
  }}
  .finding.critical {{ border-left-color:var(--red); }}
  .finding.high     {{ border-left-color:var(--amber); }}
  .finding.medium   {{ border-left-color:#ffcc33; }}
  .finding.low      {{ border-left-color:var(--cyan); }}
  .finding.info     {{ border-left-color:var(--dim); }}
  .sev {{
    display:inline-block; padding:2px 8px; border-radius:3px;
    font-size:.7rem; font-weight:700; text-transform:uppercase;
    letter-spacing:.1em; margin-right:.5rem;
  }}
  .sev.critical {{ background:var(--red); color:#fff; }}
  .sev.high     {{ background:var(--amber); color:#000; }}
  .sev.medium   {{ background:#ffcc33; color:#000; }}
  .sev.low      {{ background:var(--cyan); color:#000; }}
  .sev.info     {{ background:var(--dim); color:#fff; }}
  .tool {{
    background:var(--panel); padding:1rem; border-radius:4px; margin:1rem 0;
  }}
  .tool-header {{
    display:flex; justify-content:space-between; align-items:center;
    padding-bottom:.5rem; border-bottom:1px solid var(--purple-hi);
    margin-bottom:.8rem;
  }}
  .tool-name {{ font-family:'Orbitron',monospace; color:var(--cyan);
                font-size:1.1rem; }}
  .tool-meta {{ color:var(--dim); font-size:.8rem; }}
  .cmd {{
    background:#000; color:var(--green); padding:.6rem 1rem;
    font-family:'Share Tech Mono',monospace; font-size:.85rem;
    border-radius:3px; overflow-x:auto; white-space:pre-wrap;
  }}
  pre.output {{
    background:#000; color:#bbb; padding:.8rem; border-radius:3px;
    font-family:'Share Tech Mono',monospace; font-size:.75rem;
    max-height:400px; overflow:auto; margin-top:.6rem;
    white-space:pre-wrap; word-break:break-all;
  }}
  .footer {{ color:var(--dim); font-size:.75rem; text-align:center;
             margin-top:3rem; padding-top:1rem;
             border-top:1px solid var(--purple); }}
  .summary-counts {{ display:flex; gap:1rem; margin:1rem 0; flex-wrap:wrap; }}
  .count-pill {{
    background:var(--panel); padding:.5rem 1rem; border-radius:20px;
    font-family:'Orbitron',monospace; font-size:.85rem;
  }}
  .count-pill .n {{ font-size:1.1rem; font-weight:700; margin-right:.4rem; }}
</style>
</head><body>

<div class="banner">
  <h1>🔥 ERR0RS PENTEST REPORT</h1>
  <div class="meta">
    <div><div class="k">Target</div><div class="v">{target}</div></div>
    <div><div class="k">Goal</div><div class="v">{goal}</div></div>
    <div><div class="k">Tools Run</div><div class="v">{tools_run}</div></div>
    <div><div class="k">Findings</div><div class="v">{total_findings}</div></div>
  </div>
</div>

<h2>Executive Summary</h2>
<div class="summary-counts">{count_pills}</div>

<h2>Critical & High Findings</h2>
{high_sev_section}

<h2>All Findings by Tool</h2>
{tool_sections}

<div class="footer">
  Generated by ERR0RS Ultimate — {timestamp}<br>
  Operator: Eros Holden / Gnosisone · Pi 5 Cyberdeck · Kali ARM64
</div>
</body></html>
"""


def _severity_counts(findings):
    counts = {"critical":0,"high":0,"medium":0,"low":0,"info":0}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    return counts


def _render_finding(f):
    det = ""
    if f.detail:
        try:
            det = f"<br><small style='color:var(--dim);'>{html.escape(json.dumps(f.detail, default=str)[:200])}</small>"
        except Exception:
            pass
    return f"""<div class="finding {f.severity}">
      <span class="sev {f.severity}">{f.severity}</span>
      <strong>[{html.escape(f.kind)}]</strong> {html.escape(f.value)}{det}
    </div>"""


def _render_tool(run):
    icon = "✅" if run.success else "❌"
    cmd = html.escape(run.command or f"{run.tool} " + " ".join(run.args))
    stdout_safe = html.escape(run.stdout[:6000]) if run.stdout else "(no output)"
    findings_html = "".join(_render_finding(f) for f in run.findings) or "<em style='color:var(--dim);'>No parseable findings.</em>"
    return f"""<div class="tool">
      <div class="tool-header">
        <span class="tool-name">{icon} {run.tool.upper()}</span>
        <span class="tool-meta">rc={run.returncode} · {run.duration:.1f}s</span>
      </div>
      <div class="cmd">$ {cmd}</div>
      <div style="margin-top:.8rem;">{findings_html}</div>
      <details style="margin-top:.6rem;">
        <summary style="cursor:pointer;color:var(--purple-hi);
                 font-family:'Orbitron',monospace;font-size:.8rem;">
          📄 Full stdout (click to expand)
        </summary>
        <pre class="output">{stdout_safe}</pre>
      </details>
    </div>"""


def generate(state, output_dir="/tmp"):
    """Generate HTML report from OperatorState. Returns path to written file."""
    target = state.target or "unknown"
    goal   = state.goal or "manual exploration"
    tools_run = len(state.history)
    total_findings = len(state.findings)

    counts = _severity_counts(state.findings)
    count_pills = "".join(
        f'<div class="count-pill"><span class="n" style="color:var(--{"red" if k=="critical" else "amber" if k=="high" else "cyan" if k=="low" else "dim"});">{v}</span>{k}</div>'
        for k,v in counts.items() if v > 0
    ) or '<div class="count-pill">0 findings</div>'

    high_sev = [f for f in state.findings if f.severity in ("critical","high")]
    if high_sev:
        high_sev_section = "".join(_render_finding(f) for f in high_sev)
    else:
        high_sev_section = "<p style='color:var(--dim);'>No critical or high severity findings.</p>"

    tool_sections = "".join(_render_tool(r) for r in state.history) if state.history else "<p style='color:var(--dim);'>No tools executed.</p>"

    html_out = HTML_TEMPLATE.format(
        target=html.escape(target),
        goal=html.escape(goal),
        tools_run=tools_run,
        total_findings=total_findings,
        count_pills=count_pills,
        high_sev_section=high_sev_section,
        tool_sections=tool_sections,
        timestamp=time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime()),
    )

    # Write file
    safe_target = "".join(c if c.isalnum() else "_" for c in target)[:40]
    stamp = time.strftime("%Y%m%d-%H%M%S")
    path = Path(output_dir) / f"err0rs_report_{safe_target}_{stamp}.html"
    path.write_text(html_out, encoding="utf-8")
    return str(path)
