"""
ERR0RS ULTIMATE - Professional HTML Report Engine
=====================================================
This generates the actual pentest reports. Full professional quality.

ARCHITECTURE:
-------------
1. ReportEngine takes an EngagementSession + ReportConfig
2. It pulls all findings, sorts by severity
3. It generates executive summary (non-technical)
4. It generates technical findings (per-finding detail)
5. It attaches education from the knowledge base
6. It renders everything into a single HTML file

The HTML is self-contained: all CSS is inlined. No external deps.
You can open it in any browser, print it, or convert to PDF.

TEACHING NOTE ON REPORTS:
-------------------------
Professional pentest reports have a specific structure that clients
expect. This engine follows that structure exactly:
  - Cover page with engagement details
  - Executive summary (risk overview, business impact)
  - Findings summary dashboard (counts by severity)
  - Detailed findings (each with proof, remediation, education)
  - Remediation roadmap (prioritized action list)
  - Appendix (raw tool output, methodology notes)
"""

import sys
import os
from datetime import datetime
from typing import List, Dict

# Add parent to path so we can import core models
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from core.models import (
    EngagementSession, Finding, ScanResult,
    Severity, PentestPhase, ReportConfig
)


class HTMLReportEngine:
    """
    Generates a full professional HTML pentest report.
    One call to .generate() produces the complete report string.
    """

    def __init__(self, config: ReportConfig = None):
        self.config = config or ReportConfig()

    def generate(self, session: EngagementSession) -> str:
        """
        Main entry point. Returns a complete HTML document string.
        """
        findings = session.all_findings

        # Sort findings by severity (Critical first)
        findings.sort(key=lambda f: f.severity.priority_order)

        # Apply severity filter if configured
        if self.config.severity_filter:
            min_priority = self.config.severity_filter.priority_order
            findings = [f for f in findings if f.severity.priority_order <= min_priority]

        summary = session.finding_summary

        html_parts = [
            self._render_doctype_and_head(),
            self._render_css(),
            self._render_cover_page(session),
            self._render_executive_summary(session, summary) if self.config.include_executive else "",
            self._render_findings_dashboard(summary, session),
            self._render_findings_detail(findings),
            self._render_remediation_roadmap(findings) if self.config.include_remediation else "",
            self._render_timeline(session) if self.config.include_timeline else "",
            self._render_appendix(session) if self.config.include_raw_output else "",
            self._render_footer(),
            "</body></html>",
        ]
        return "\n".join(html_parts)

    # -----------------------------------------------------------------------
    # DOCUMENT STRUCTURE
    # -----------------------------------------------------------------------

    def _render_doctype_and_head(self) -> str:
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{self.config.company_name} — Security Assessment Report</title>
</head>"""

    def _render_footer(self) -> str:
        return f"""
<div class="report-footer">
    <p>Generated by <strong>ERR0RS ULTIMATE</strong> — AI-Powered Security Assessment Framework</p>
    <p>Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
    <p class="confidential">⚠️ CONFIDENTIAL — This report contains sensitive security information.
    Distribute only to authorized personnel.</p>
</div>"""

    # -----------------------------------------------------------------------
    # FULL PROFESSIONAL CSS — Self-contained, no external deps
    # -----------------------------------------------------------------------

    def _render_css(self) -> str:
        return """<style>
/* === RESET & BASE === */
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
    color: #1a1a2e;
    background: #f0f2f5;
    line-height: 1.6;
}
a { color: #6c3cc2; text-decoration: none; }
a:hover { text-decoration: underline; }

/* === COVER PAGE === */
.cover-page {
    min-height: 100vh;
    background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
    color: #fff;
    padding: 60px 40px;
    position: relative;
}
.cover-page::before {
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0; bottom: 0;
    background: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.03'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
    opacity: 1;
}
.cover-logo { font-size: 72px; margin-bottom: 10px; position: relative; }
.cover-title { font-size: 42px; font-weight: 700; letter-spacing: 2px; position: relative; }
.cover-subtitle { font-size: 18px; color: #a0a0c0; margin-top: 8px; position: relative; }
.cover-meta {
    margin-top: 60px;
    position: relative;
    background: rgba(255,255,255,0.08);
    border: 1px solid rgba(255,255,255,0.15);
    border-radius: 12px;
    padding: 30px 50px;
}
.cover-meta table { width: 100%; border-collapse: collapse; }
.cover-meta td { padding: 8px 16px; font-size: 15px; }
.cover-meta td:first-child { color: #a0a0c0; text-align: right; width: 140px; }
.cover-meta td:last-child { color: #fff; text-align: left; font-weight: 500; }
.cover-confidential {
    margin-top: 40px;
    position: relative;
    color: #ff6b6b;
    font-size: 13px;
    letter-spacing: 3px;
    text-transform: uppercase;
    font-weight: 600;
}

/* === SECTIONS === */
.report-section {
    max-width: 1100px;
    margin: 40px auto;
    background: #fff;
    border-radius: 12px;
    box-shadow: 0 2px 20px rgba(0,0,0,0.08);
    overflow: hidden;
}
.section-header {
    background: linear-gradient(135deg, #1a1a2e, #16213e);
    color: #fff;
    padding: 28px 40px;
    display: flex;
    align-items: center;
    gap: 16px;
}
.section-header h2 { font-size: 22px; font-weight: 600; }
.section-header .icon { font-size: 28px; }
.section-body { padding: 32px 40px; }

/* === SEVERITY BADGES === */
.badge {
    display: inline-block;
    padding: 4px 12px;
    border-radius: 20px;
    font-size: 13px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}
.badge-critical { background: #ff2d2d; color: #fff; }
.badge-high     { background: #ff8c00; color: #fff; }
.badge-medium   { background: #ffd700; color: #1a1a2e; }
.badge-low      { background: #4caf50; color: #fff; }
.badge-info     { background: #2196f3; color: #fff; }

/* === DASHBOARD CARDS === */
.dashboard { display: flex; gap: 20px; flex-wrap: wrap; }
.dash-card {
    flex: 1; min-width: 140px;
    border-radius: 12px;
    padding: 24px;
    text-align: center;
    color: #fff;
    box-shadow: 0 4px 15px rgba(0,0,0,0.15);
}
.dash-card .number { font-size: 42px; font-weight: 800; }
.dash-card .label  { font-size: 14px; opacity: 0.9; margin-top: 4px; text-transform: uppercase; letter-spacing: 1px; }
.dash-critical { background: linear-gradient(135deg, #ff2d2d, #c0392b); }
.dash-high     { background: linear-gradient(135deg, #ff8c00, #e67e22); }
.dash-medium   { background: linear-gradient(135deg, #ffd700, #f39c12); color: #1a1a2e; }
.dash-low      { background: linear-gradient(135deg, #4caf50, #27ae60); }
.dash-info     { background: linear-gradient(135deg, #2196f3, #2980b9); }
.dash-total    { background: linear-gradient(135deg, #6c3cc2, #9b59b6); }

/* === FINDING CARDS === */
.finding-card {
    border: 1px solid #e8e8e8;
    border-radius: 10px;
    margin-bottom: 24px;
    overflow: hidden;
    transition: box-shadow 0.2s;
}
.finding-card:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
.finding-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 18px 24px;
    background: #fafafa;
    border-bottom: 1px solid #eee;
    gap: 12px;
}
.finding-header h3 { font-size: 17px; flex: 1; }
.finding-meta { display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }
.finding-meta span { font-size: 12px; color: #888; background: #f0f0f0; padding: 3px 10px; border-radius: 12px; }
.finding-body { padding: 20px 24px; }
.finding-body h4 { color: #6c3cc2; margin: 16px 0 6px; font-size: 15px; }
.finding-body p, .finding-body pre { margin-bottom: 10px; font-size: 14px; color: #444; }
.finding-body pre {
    background: #1a1a2e;
    color: #a8e6cf;
    padding: 14px 18px;
    border-radius: 8px;
    overflow-x: auto;
    font-size: 13px;
    line-height: 1.5;
    white-space: pre-wrap;
}
.finding-body ul { padding-left: 20px; }
.finding-body ul li { margin-bottom: 6px; font-size: 14px; color: #444; }
.references-list a { display: block; font-size: 13px; color: #6c3cc2; margin-bottom: 4px; }

/* === EDUCATION CARDS === */
.education-card {
    background: linear-gradient(135deg, #eef2ff, #f0e6ff);
    border: 1px solid #d4c5f5;
    border-radius: 10px;
    margin-top: 18px;
    overflow: hidden;
}
.edu-header {
    background: linear-gradient(135deg, #6c3cc2, #9b59b6);
    color: #fff;
    padding: 12px 20px;
    display: flex;
    align-items: center;
    gap: 10px;
}
.edu-header h3 { font-size: 15px; flex: 1; }
.edu-difficulty { font-size: 11px; padding: 2px 10px; border-radius: 10px; background: rgba(255,255,255,0.2); }
.edu-section { padding: 12px 20px; border-bottom: 1px solid #ddd; }
.edu-section:last-child { border-bottom: none; }
.edu-section strong { color: #6c3cc2; display: block; margin-bottom: 4px; font-size: 13px; }
.edu-section p { font-size: 13px; color: #555; white-space: pre-line; }
.edu-section ul { padding-left: 18px; }
.edu-section ul li { font-size: 13px; color: #555; margin-bottom: 3px; }

/* === REMEDIATION ROADMAP === */
.roadmap-item {
    display: flex;
    gap: 16px;
    margin-bottom: 16px;
    align-items: flex-start;
}
.roadmap-priority {
    min-width: 44px;
    height: 44px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 800;
    color: #fff;
    font-size: 18px;
    flex-shrink: 0;
}
.roadmap-content { flex: 1; }
.roadmap-content h4 { font-size: 15px; margin-bottom: 4px; }
.roadmap-content p { font-size: 13px; color: #666; }

/* === TIMELINE === */
.timeline { position: relative; padding-left: 30px; }
.timeline::before { content: ''; position: absolute; left: 14px; top: 0; bottom: 0; width: 2px; background: #ddd; }
.timeline-item { position: relative; margin-bottom: 20px; }
.timeline-item::before { content: ''; position: absolute; left: -22px; top: 6px; width: 14px; height: 14px; border-radius: 50%; background: #6c3cc2; border: 3px solid #fff; box-shadow: 0 0 0 2px #6c3cc2; }
.timeline-item h4 { font-size: 14px; color: #1a1a2e; }
.timeline-item p { font-size: 13px; color: #888; }

/* === EXEC SUMMARY === */
.risk-box {
    border-radius: 10px;
    padding: 20px 24px;
    margin-bottom: 16px;
}
.risk-box h4 { margin-bottom: 8px; font-size: 16px; }
.risk-box p { font-size: 14px; color: #444; }
.risk-critical { background: #fff0f0; border-left: 4px solid #ff2d2d; }
.risk-high     { background: #fff5ee; border-left: 4px solid #ff8c00; }
.risk-summary  { background: #f8f9fa; border: 1px solid #e9ecef; }

/* === FOOTER === */
.report-footer {
    max-width: 1100px;
    margin: 60px auto 40px;
    text-align: center;
    color: #999;
    font-size: 13px;
}
.report-footer .confidential { color: #ff2d2d; font-weight: 600; margin-top: 8px; }

/* === PRINT STYLES === */
@media print {
    .cover-page { min-height: auto; page-break-after: always; }
    .report-section { page-break-inside: avoid; box-shadow: none; border: 1px solid #ddd; }
}
</style>
<body>"""

    # -----------------------------------------------------------------------
    # COVER PAGE
    # -----------------------------------------------------------------------

    def _render_cover_page(self, session: EngagementSession) -> str:
        end_date = session.ended_at.strftime('%Y-%m-%d') if session.ended_at else "Ongoing"
        return f"""
<div class="cover-page">
    <div class="cover-logo">🐱</div>
    <div class="cover-title">ERR0RS ULTIMATE</div>
    <div class="cover-subtitle">AI-Powered Security Assessment Report</div>
    <div class="cover-meta">
        <table>
            <tr><td>Engagement:</td><td>{session.name}</td></tr>
            <tr><td>Client:</td><td>{session.client_name or 'N/A'}</td></tr>
            <tr><td>Tester:</td><td>{session.tester_name or 'N/A'}</td></tr>
            <tr><td>Targets:</td><td>{', '.join(session.targets) if session.targets else 'N/A'}</td></tr>
            <tr><td>Start Date:</td><td>{session.started_at.strftime('%Y-%m-%d')}</td></tr>
            <tr><td>End Date:</td><td>{end_date}</td></tr>
            <tr><td>Status:</td><td>{session.status.capitalize()}</td></tr>
        </table>
    </div>
    <div class="cover-confidential">⚠ Confidential</div>
</div>"""

    # -----------------------------------------------------------------------
    # EXECUTIVE SUMMARY — Non-technical. Business language.
    # -----------------------------------------------------------------------
    # TEACHING NOTE: This section is written for people who sign the checks.
    # No CVE numbers. No technical jargon. Risk. Business impact. Period.
    # -----------------------------------------------------------------------

    def _render_executive_summary(self, session: EngagementSession, summary: Dict[str, int]) -> str:
        total = sum(summary.values())
        risk_level = "Critical" if summary["Critical"] > 0 else \
                     "High" if summary["High"] > 0 else \
                     "Medium" if summary["Medium"] > 0 else \
                     "Low"

        risk_colors = {"Critical": "#ff2d2d", "High": "#ff8c00", "Medium": "#ffd700", "Low": "#4caf50"}
        risk_classes = {"Critical": "risk-critical", "High": "risk-high", "Medium": "risk-summary", "Low": "risk-summary"}

        # Build risk narrative for exec audience
        narratives = []
        if summary["Critical"] > 0:
            narratives.append(
                f"<div class='risk-box risk-critical'>"
                f"<h4 style='color:#ff2d2d;'>⚠️ Critical Risk — Immediate Action Required</h4>"
                f"<p>{summary['Critical']} critical vulnerabilities were identified that could allow "
                f"an attacker to gain full, unrestricted access to systems and data. "
                f"These must be remediated immediately.</p></div>"
            )
        if summary["High"] > 0:
            narratives.append(
                f"<div class='risk-box risk-high'>"
                f"<h4 style='color:#ff8c00;'>⚡ High Risk — Address Within 7 Days</h4>"
                f"<p>{summary['High']} high-severity vulnerabilities were found that present "
                f"significant risk to the organization if exploited. These require urgent attention.</p></div>"
            )

        return f"""
<div class="report-section">
    <div class="section-header">
        <span class="icon">📋</span>
        <h2>Executive Summary</h2>
    </div>
    <div class="section-body">
        <div class="risk-box risk-summary">
            <h4 style="color: {risk_colors[risk_level]};">Overall Risk Assessment: {risk_level}</h4>
            <p>This assessment identified <strong>{total} total findings</strong> across
            the tested infrastructure. The overall risk posture is rated <strong>{risk_level}</strong>.
            A detailed breakdown and remediation roadmap follows in this report.</p>
        </div>
        {"".join(narratives)}
        <h4 style="margin-top:24px; margin-bottom:10px;">Scope of Testing</h4>
        <p>Targets assessed: <strong>{', '.join(session.targets) if session.targets else 'N/A'}</strong></p>
        <p style="margin-top:6px;">{session.scope_notes or 'Standard penetration test scope applied.'}</p>
    </div>
</div>"""

    # -----------------------------------------------------------------------
    # FINDINGS DASHBOARD — The visual summary. Numbers at a glance.
    # -----------------------------------------------------------------------

    def _render_findings_dashboard(self, summary: Dict[str, int], session: EngagementSession) -> str:
        total = sum(summary.values())
        return f"""
<div class="report-section">
    <div class="section-header">
        <span class="icon">📊</span>
        <h2>Findings Dashboard</h2>
    </div>
    <div class="section-body">
        <div class="dashboard">
            <div class="dash-card dash-total"><div class="number">{total}</div><div class="label">Total Findings</div></div>
            <div class="dash-card dash-critical"><div class="number">{summary['Critical']}</div><div class="label">Critical</div></div>
            <div class="dash-card dash-high"><div class="number">{summary['High']}</div><div class="label">High</div></div>
            <div class="dash-card dash-medium"><div class="number">{summary['Medium']}</div><div class="label">Medium</div></div>
            <div class="dash-card dash-low"><div class="number">{summary['Low']}</div><div class="label">Low</div></div>
            <div class="dash-card dash-info"><div class="number">{summary['Info']}</div><div class="label">Info</div></div>
        </div>
        <p style="margin-top:20px; color:#888; font-size:13px;">
            Scans performed: <strong>{len(session.scan_results)}</strong> &nbsp;|&nbsp;
            Total duration: <strong>{session.total_duration_seconds:.1f}s</strong> &nbsp;|&nbsp;
            Targets: <strong>{len(session.targets)}</strong>
        </p>
    </div>
</div>"""

    # -----------------------------------------------------------------------
    # DETAILED FINDINGS — The meat of the report
    # -----------------------------------------------------------------------
    # Each finding gets: title, severity, tool, target, description,
    # proof/evidence, remediation steps, education block, and references.
    # This is what the IT team actually uses to fix things.
    # -----------------------------------------------------------------------

    def _render_findings_detail(self, findings: List[Finding]) -> str:
        if not findings:
            return """
<div class="report-section">
    <div class="section-header"><span class="icon">🔍</span><h2>Detailed Findings</h2></div>
    <div class="section-body"><p style="color:#4caf50; font-weight:600;">✅ No findings. The tested scope is clean.</p></div>
</div>"""

        cards = []
        for i, f in enumerate(findings, 1):
            badge_class = f"badge-{f.severity.value.lower()}"
            edu_html = ""

            # Attach education if enabled
            if self.config.include_education and f.education:
                edu_html = f.education  # Pre-rendered HTML from knowledge base

            proof_html = f"<h4>🔬 Proof / Evidence</h4><pre>{f.proof}</pre>" if f.proof else ""
            raw_html   = f"<h4>📝 Raw Output</h4><pre>{f.raw_output}</pre>" if f.raw_output and self.config.include_raw_output else ""

            remed_html = ""
            if self.config.include_remediation and f.remediation:
                remed_items = f.remediation.split("\n")
                remed_html = "<h4>🛡️ Remediation Steps</h4><ul>"
                for step in remed_items:
                    step = step.strip().lstrip("0123456789.- ")
                    if step:
                        remed_html += f"<li>{step}</li>"
                remed_html += "</ul>"

            refs_html = ""
            if f.references:
                refs_html = '<h4>📎 References</h4><div class="references-list">'
                for ref in f.references:
                    refs_html += f'<a href="{ref}" target="_blank">{ref}</a>'
                refs_html += "</div>"

            cards.append(f"""
<div class="finding-card">
    <div class="finding-header">
        <span class="badge {badge_class}">{f.severity.value}</span>
        <h3>#{i} — {f.title}</h3>
        <div class="finding-meta">
            <span>🛠 {f.tool_name}</span>
            <span>🎯 {f.target}</span>
            <span>📍 {f.phase.value}</span>
        </div>
    </div>
    <div class="finding-body">
        <h4>📄 Description</h4>
        <p>{f.description}</p>
        {proof_html}
        {raw_html}
        {remed_html}
        {refs_html}
        {edu_html}
    </div>
</div>""")

        return f"""
<div class="report-section">
    <div class="section-header"><span class="icon">🔍</span><h2>Detailed Findings</h2></div>
    <div class="section-body">{"".join(cards)}</div>
</div>"""

    # -----------------------------------------------------------------------
    # REMEDIATION ROADMAP — Prioritized action plan
    # -----------------------------------------------------------------------
    # TEACHING NOTE: This is what clients actually ACT on. It takes all
    # findings and turns them into a prioritized "fix this first, then this"
    # action plan. Business value: tells them WHERE to spend money first.
    # -----------------------------------------------------------------------

    def _render_remediation_roadmap(self, findings: List[Finding]) -> str:
        if not findings:
            return ""

        # Group by severity for priority ordering
        grouped = {"Critical": [], "High": [], "Medium": [], "Low": [], "Info": []}
        for f in findings:
            grouped[f.severity.value].append(f)

        items_html = ""
        priority_num = 1
        priority_colors = {"Critical": "#ff2d2d", "High": "#ff8c00", "Medium": "#ffd700", "Low": "#4caf50", "Info": "#2196f3"}
        timeframes = {"Critical": "Immediately (< 24 hours)", "High": "Within 7 days", "Medium": "Within 30 days", "Low": "Within 90 days", "Info": "Next review cycle"}

        for severity in ["Critical", "High", "Medium", "Low", "Info"]:
            if not grouped[severity]:
                continue
            for f in grouped[severity]:
                items_html += f"""
<div class="roadmap-item">
    <div class="roadmap-priority" style="background:{priority_colors[severity]};">{priority_num}</div>
    <div class="roadmap-content">
        <h4>{f.title} <span class="badge badge-{severity.lower()}">{severity}</span></h4>
        <p><strong>Target:</strong> {f.target} &nbsp;|&nbsp;
           <strong>Tool:</strong> {f.tool_name} &nbsp;|&nbsp;
           <strong>Timeline:</strong> {timeframes[severity]}</p>
        <p style="margin-top:4px;">{f.remediation if f.remediation else 'See detailed finding for remediation steps.'}</p>
    </div>
</div>"""
                priority_num += 1

        return f"""
<div class="report-section">
    <div class="section-header"><span class="icon">🛡️</span><h2>Remediation Roadmap</h2></div>
    <div class="section-body">
        <p style="margin-bottom:20px; color:#666;">
            The following action items are prioritized by severity. Address critical
            findings first. Each item includes the recommended timeframe for remediation.
        </p>
        {items_html}
    </div>
</div>"""

    # -----------------------------------------------------------------------
    # TIMELINE — Visual log of what happened and when
    # -----------------------------------------------------------------------

    def _render_timeline(self, session: EngagementSession) -> str:
        if not session.scan_results:
            return ""

        items_html = ""
        for result in sorted(session.scan_results, key=lambda r: r.started_at or datetime.min):
            time_str = result.started_at.strftime('%Y-%m-%d %H:%M') if result.started_at else "Unknown"
            status_emoji = {"success": "✅", "failed": "❌", "timeout": "⏰", "running": "🔄", "pending": "⏳"}
            emoji = status_emoji.get(result.status.value, "🔲")
            items_html += f"""
<div class="timeline-item">
    <h4>{emoji} {result.tool_name} — {result.phase.value}</h4>
    <p>{time_str} &nbsp;|&nbsp; {result.finding_count} findings &nbsp;|&nbsp; {result.duration:.1f}s &nbsp;|&nbsp; Target: {result.target}</p>
</div>"""

        return f"""
<div class="report-section">
    <div class="section-header"><span class="icon">📅</span><h2>Engagement Timeline</h2></div>
    <div class="section-body">
        <div class="timeline">{items_html}</div>
    </div>
</div>"""

    # -----------------------------------------------------------------------
    # APPENDIX — Raw output for the deep-dive analysts
    # -----------------------------------------------------------------------

    def _render_appendix(self, session: EngagementSession) -> str:
        appendix_html = ""
        for result in session.scan_results:
            if result.raw_output:
                appendix_html += f"""
<h4 style="margin-top:20px; color:#6c3cc2;">📌 {result.tool_name} — {result.target} ({result.phase.value})</h4>
<p style="font-size:12px; color:#999;">Command: <code>{result.command}</code></p>
<pre>{result.raw_output[:2000]}{"..." if len(result.raw_output) > 2000 else ""}</pre>"""

        if not appendix_html:
            appendix_html = "<p style='color:#999;'>No raw output captured.</p>"

        return f"""
<div class="report-section">
    <div class="section-header"><span class="icon">📁</span><h2>Appendix — Raw Tool Output</h2></div>
    <div class="section-body">{appendix_html}</div>
</div>"""
