"""
ERR0RS BadUSB Studio - DuckyScript to CircuitPython Converter
Converts standard DuckyScript payloads to CircuitPython HID scripts for RP2040
"""

# Key mappings: DuckyScript key names -> CircuitPython Keycode names
KEYCODE_MAP = {
    "ENTER": "Keycode.ENTER",
    "ESCAPE": "Keycode.ESCAPE",
    "ESC": "Keycode.ESCAPE",
    "BACKSPACE": "Keycode.BACKSPACE",
    "TAB": "Keycode.TAB",
    "SPACE": "Keycode.SPACE",
    "CAPSLOCK": "Keycode.CAPS_LOCK",
    "DELETE": "Keycode.DELETE",
    "END": "Keycode.END",
    "HOME": "Keycode.HOME",
    "INSERT": "Keycode.INSERT",
    "PAGEUP": "Keycode.PAGE_UP",
    "PAGEDOWN": "Keycode.PAGE_DOWN",
    "UP": "Keycode.UP_ARROW",
    "DOWN": "Keycode.DOWN_ARROW",
    "LEFT": "Keycode.LEFT_ARROW",
    "RIGHT": "Keycode.RIGHT_ARROW",
    "F1": "Keycode.F1", "F2": "Keycode.F2", "F3": "Keycode.F3",
    "F4": "Keycode.F4", "F5": "Keycode.F5", "F6": "Keycode.F6",
    "F7": "Keycode.F7", "F8": "Keycode.F8", "F9": "Keycode.F9",
    "F10": "Keycode.F10", "F11": "Keycode.F11", "F12": "Keycode.F12",
    "PRINTSCREEN": "Keycode.PRINT_SCREEN",
    "SCROLLLOCK": "Keycode.SCROLL_LOCK",
    "PAUSE": "Keycode.PAUSE",
    "NUMLOCK": "Keycode.KEYPAD_NUMLOCK",
    "APP": "Keycode.APPLICATION",
    "MENU": "Keycode.APPLICATION",
    "WINDOWS": "Keycode.WINDOWS",
    "GUI": "Keycode.WINDOWS",
    "COMMAND": "Keycode.COMMAND",
    "SHIFT": "Keycode.SHIFT",
    "ALT": "Keycode.ALT",
    "CTRL": "Keycode.CONTROL",
    "CONTROL": "Keycode.CONTROL",
}

CIRCUITPYTHON_HEADER = '''"""
Auto-generated by ERR0RS BadUSB Studio
RP2040 CircuitPython HID Payload
"""
import time
import usb_hid
from adafruit_hid.keyboard import Keyboard
from adafruit_hid.keyboard_layout_us import KeyboardLayoutUS
from adafruit_hid.keycode import Keycode

kbd = Keyboard(usb_hid.devices)
layout = KeyboardLayoutUS(kbd)

time.sleep(2)  # Wait for OS to recognise device

'''


class DuckyConverter:
    """Convert DuckyScript payloads to CircuitPython for RP2040"""

    def convert(self, ducky_script: str) -> str:
        """
        Main conversion entry point.
        Returns a complete CircuitPython .py file as a string.
        """
        lines = ducky_script.strip().splitlines()
        output_lines = [CIRCUITPYTHON_HEADER]
        skip_rem_block = False

        for raw_line in lines:
            line = raw_line.strip()

            # Skip blank lines
            if not line:
                output_lines.append("")
                continue

            # REM_BLOCK / END_REM handling
            if line.upper().startswith("REM_BLOCK"):
                skip_rem_block = True
                continue
            if line.upper() == "END_REM":
                skip_rem_block = False
                continue
            if skip_rem_block:
                continue

            converted = self._convert_line(line)
            if converted is not None:
                output_lines.append(converted)

        return "\n".join(output_lines)

    def _convert_line(self, line: str) -> str | None:
        """Convert a single DuckyScript line to CircuitPython"""
        upper = line.upper()

        # Comments
        if upper.startswith("REM ") or upper == "REM":
            return f"# {line[4:]}"

        # ATTACKMODE / EXTENSION - RP2040 firmware handles this natively
        if upper.startswith("ATTACKMODE") or upper.startswith("EXTENSION"):
            return f"# [HARDWARE] {line}"

        # DEFINE - store as Python constant
        if upper.startswith("DEFINE "):
            parts = line.split(None, 2)
            if len(parts) >= 3:
                name = parts[1].lstrip("#").replace("-", "_")
                value = parts[2]
                return f"{name} = {repr(value)}  # DEFINE"
            return f"# DEFINE: {line}"

        # DELAY
        if upper.startswith("DELAY "):
            ms = line.split(None, 1)[1].strip()
            try:
                return f"time.sleep({int(ms) / 1000:.3f})"
            except ValueError:
                return f"time.sleep({ms} / 1000)  # DELAY"

        # STRING (no newline)
        if upper.startswith("STRING "):
            text = line[7:]
            return f"layout.write({repr(text)})"

        # STRINGLN (string + enter)
        if upper.startswith("STRINGLN "):
            text = line[9:]
            return (
                f"layout.write({repr(text)})\n"
                f"kbd.press(Keycode.ENTER)\nkbd.release_all()"
            )

        # ENTER standalone
        if upper == "ENTER":
            return "kbd.press(Keycode.ENTER)\nkbd.release_all()"

        # Modifier combos: GUI r, CTRL_SHIFT ENTER, ALT F4, etc.
        if self._is_combo(upper):
            return self._convert_combo(line)

        # Single special keys
        if upper in KEYCODE_MAP:
            kc = KEYCODE_MAP[upper]
            return f"kbd.press({kc})\nkbd.release_all()"

        # VAR / IF / WHILE / END_IF / END_WHILE - approximate with comments
        if upper.startswith(("VAR ", "IF ", "WHILE ", "END_IF", "END_WHILE", "ELSE")):
            return f"# [LOGIC] {line}  # Convert logic manually if needed"

        # Catch-all
        return f"# [UNHANDLED] {line}"

    def _is_combo(self, upper: str) -> bool:
        """Detect modifier+key combos"""
        combo_starters = [
            "GUI ", "WINDOWS ", "ALT ", "CTRL ", "CTRL_ALT ", "CTRL_SHIFT ",
            "ALT_SHIFT ", "SHIFT ", "COMMAND "
        ]
        return any(upper.startswith(s) for s in combo_starters)

    def _convert_combo(self, line: str) -> str:
        """Convert modifier+key combo to CircuitPython press sequence"""
        parts = line.split()
        keys = []

        for part in parts:
            upper_part = part.upper()
            # Handle compound modifiers like CTRL_SHIFT
            if "_" in upper_part:
                for sub in upper_part.split("_"):
                    if sub in KEYCODE_MAP:
                        keys.append(KEYCODE_MAP[sub])
            elif upper_part in KEYCODE_MAP:
                keys.append(KEYCODE_MAP[upper_part])
            elif len(part) == 1:
                # Single character key
                keys.append(f"Keycode.{part.upper()}")

        if keys:
            press_args = ", ".join(keys)
            return f"kbd.press({press_args})\nkbd.release_all()"
        return f"# [COMBO UNRESOLVED] {line}"

    def save_converted(self, content: str, filename: str = "code.py") -> str:
        """Save converted CircuitPython script to local payloads directory"""
        from pathlib import Path
        out_dir = Path(__file__).parent / "payloads" / "local"
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / filename
        out_path.write_text(content, encoding="utf-8")
        return str(out_path)
